### ISSUE TITLE
empty response due to missing "0" byte at the end of command ADPU

### ISSUE THREAD

**Issue by bam80** [estkme-group/lpac#118] opened 2024-06-14 23:02 UTC
I sniffed MBIM traffic on Windows via Wireshark and realized the difference in the last byte of the ADPUs compared to what we get with `stdio` backend of lpac.
It seems lpac missing the last "0" byte there.

For example, here what we have in Windows for "chip info" ADPU command ([the sniffed packet](https://github.com/user-attachments/files/15844673/Chip.info.ADPU.pcapng.gz)):
![image](https://github.com/estkme-group/lpac/assets/233979/1a854dd2-f01f-494a-b52c-da2589425ce3)
As we see, the command ends with `...015a00` byte sequence, with the `0x00` byte at the end.

In lpac (via [MBIM wrapper](https://github.com/stich86/lpac-libmbim-wrapper)), we get the same ADPU command but without the last `0x00` byte:
```
$ DEBUG=1 ./lpac-mbim --device=/dev/cdc-wdm0 chip info
recv={"type":"apdu","payload":{"func":"connect","param":null}}
INFO: Connect
send={"type": "apdu", "payload": {"ecode": 0}}
recv={"type":"apdu","payload":{"func":"logic_channel_open","param":"a0000005591010ffffffff8900000100"}}
INFO: Open channel with AID a0000005591010ffffffff8900000100
send={"type": "apdu", "payload": {"ecode": 1}}
recv={"type":"apdu","payload":{"func":"transmit","param":"81e2910006bf3e035c015a"}}
Send APDU: 81e2910006bf3e035c015a
Recv APDU: 9000
send={"type": "apdu", "payload": {"ecode": 0, "data": "9000"}}
recv={"type":"lpa","payload":{"code":-1,"message":"es10c_get_eid","data":""}}
INFO: Received LPA data. Printing...
{'payload': {'code': -1, 'data': '', 'message': 'es10c_get_eid'}, 'type': 'lpa'}
recv={"type":"apdu","payload":{"func":"logic_channel_close","param":"01"}}
INFO: Close channel 1
send={"type": "apdu", "payload": {"ecode": 0}}
recv={"type":"apdu","payload":{"func":"disconnect","param":null}}
INFO: Disconnect
...
Exit code: 255
```
The line with the ADPU is `Send APDU: 81e2910006bf3e035c015a`.

If we see the meaning of the last byte, it's responsible for "the maximum number (Ne) of response bytes expected", see [the table](https://en.wikipedia.org/wiki/Smart_card_application_protocol_data_unit#APDU_message_command-response_pair):

<table class="wikitable">
<tbody><tr>
<th colspan="3">Command APDU
</th></tr>
<tr>
<th>Field name
</th>
<th>Length (bytes)
</th>
<th>Description
</th></tr>

<tr>
<td>...
</td>
<td>...</td>
<td>...</td></tr>
<tr>

<td>L<sub>e</sub>
</td>
<td>0, 1, 2 or 3
</td>
<td>Encodes the maximum number (N<sub>e</sub>) of response bytes expected
<p><b style="color: red;">0 bytes denotes N<sub>e</sub>=0</b><br>
1 byte in the range 1 to 255 denotes that value of N<sub>e</sub>, or <b>0 denotes N<sub>e</sub>=256</b><br>
2 bytes (if extended L<sub>c</sub> was present in the command) in the range 1 to 65 535 denotes N<sub>e</sub> of that value, or two zero bytes denotes 65 536<br>
3 bytes (if L<sub>c</sub> was not present in the command), the first of which must be 0, denote N<sub>e</sub> in the same way as two-byte L<sub>e</sub>
</p>
</td></tr>
<tr>
<th colspan="3">Response APDU
</th></tr>
<tr>
<td>Response data
</td>
<td>N<sub>r</sub> (<b style="color: red;">at most N<sub>e</sub></b>)
</td>
<td>Response data
</td></tr>
<tr>
<td>SW1-SW2<br>(Response trailer)
</td>
<td>2
</td>
<td>Command processing status, e.g., 90 00 (<a href="[/wiki/Hexadecimal](view-source:https://en.wikipedia.org/wiki/Hexadecimal)" title="Hexadecimal">hexadecimal</a>) indicates success<sup id="cite_ref-celer_2-1" class="reference"><a href="[#cite_note-celer-2](view-source:https://en.wikipedia.org/wiki/Smart_card_application_protocol_data_unit#cite_note-celer-2)">[2]</a></sup>
</td></tr></tbody></table>
So if the last byte(s) is missing, there will be no response, and we see that in the output above:

```
...
Send APDU: 81e2910006bf3e035c015a
Recv APDU: 9000
...
```
where "Recv APDU: 9000" is just SW1-SW2 without the Response data.
If the last byte present and is `0x00`, there will be response of at most 256 bytes length.

Indeed, if we try it manually, we will get corresponding results:
```sh
# the last ADPU's byte is missing, the response is (null)
$ mbimcli -d /dev/cdc-wdm0 --ms-set-uicc-apdu="channel=1, classbyte-type=extended, command=81e2910006bf3e035c015a" 
Succesfully retrieved UICC APDU response:
	  status: 144
	response: (null)

# the last ADPU's byte is 0x00, the response is non-empty
$ mbimcli -d /dev/cdc-wdm0 --ms-set-uicc-apdu="channel=1, classbyte-type=extended, command=81e2910006bf3e035c015a00" 
Succesfully retrieved UICC APDU response:
	  status: 144
	response: BF:3E:12:5A:10:89:03:30:23:42:62:00:00:00:00:00:99:26:13:55:46
```

_So the easy way to fix this problem is to add `0x00` byte at the end of all command ADPU's where response is expected.
That should be harmless and correspond to the Windows behavior and to the specification._

**Comment by septs** [comment] 2024-06-15 01:51
if the is MBIM-specific, i don't think @estkme will fixit.

**Comment by bam80** [comment] 2024-06-15 09:05
Dear @septs, if you see the explanation above carefully, you will learn the problem happens on lower level than MBIM, as application protocol data unit (APDU) is a standard for smart cards and doesn't relate to MBIM in any way, and lpac just doesn't follow the standard here.

It just might happen the problem doesn't reveal itself in all the circumstances, but still it's a clear problem on lpac side which needs to be fixed, IMO.
Thanks.

**Comment by estkme** [comment] 2024-06-15 09:46
Since ths wikipedia is point out **0 bytes denotes Ne=0** that means missing Le should be same as one byte Le set '0x00'.

I think it is because your MBIM library didn't fully implement the standard, so it is better be a workaround in your wrapper.

If the issue is not updated within 24 hours, the issue will be closed.

**Comment by bam80** [comment] 2024-06-15 10:04
> Since ths wikipedia is point out 0 bytes denotes Ne=0 that means missing Le should be same as one byte Le set '0x00'.

@estkme sorry but it seems to me the Wiki (and the standard) clearly distinguish this two cases:

> - **0 bytes denotes Ne=0**
> - 1 byte in the range 1 to 255 denotes that value of Ne, or **0 denotes Ne=256**

So "0 bytes" doesn't mean the same as 1 byte `0x00`, this are two completely different cases:
in the first case you get empty response (Ne=0), in the secod - the response will be 256 bytes max (Ne=256).

That is fully confirmed by experiment above with manual `mbimcli` run.

**Comment by estkme** [comment] 2024-06-15 10:20
Your explanation also makes sense.

Since PC/SC devices, Android OMAPI/TMAPI, Serial AT Command, GBinder, and QRTR interfaces do not have this problem, fixing such a low-level behavior needs to be treated with special caution. Sometimes a problem may have become an industry standard (just Like misspelling of HTTP REFERER) Even if we eventually find out that it is indeed a bug, it is very likely that we will not fix it.

I will give an opinion reply after a detailed investigation of ISO7816 and SGP.22 and other related standard documents.

**Comment by bam80** [comment] 2024-06-15 12:06
Thank you for the care.

> Since PC/SC devices, Android OMAPI/TMAPI, Serial AT Command, GBinder, and QRTR interfaces do not have this problem,

It looks to me it doesn't depend on the device, but rather on the particular smart card itself - because it's the one who interprets ADPU and the Le bytes within it. Serial AT Commands, MBIM, QRTR etc. are just a transports here.

So it might be the cards you tested are slightly deviate from the standards and can return non-empty response even if Le byte is missing.
But the card I happen to have (which by the way is embedded in the modem, so I can't change it) - follows the standard more strictly, so the problem reveals.

To make lpac work reliably for all the cards, I think it should be addressed within lpac itself. Worth saying it's looks like a safe change, though.

But sure, please take your time and investigate the standards, to make sure we are on the right way.
I'll wait your response,
Thank you.

**Comment by septs** [comment] 2024-06-15 12:33
> But sure, please take your time and investigate the standards, to make sure we are on the right way.

I think this is coercive.

**Comment by estkme** [comment] 2024-06-15 12:35
I'm currently on vacation.

I'm sure our test set covers enough cards.

what I have tested:

Giesecke+Devrient "Hercules" which used on
iPhone XR to 11 and many Samsung phones

Giesecke+Devrient "Aries" which used on
iPhone 12 to 15 and more

Thales "WSTM068" which used on
Thinkpad eSIM
Google Pixel

Eastcompeace ST33G1M2 series which used on
5ber eSIM
esim.me eSIM

Sysmocom "sysmoEUICC1" series which used on
"Many developer"

So I don't think these are all "out of standard"

2024 年 6 月 15 日星期六 20:07, Andrey Butirsky ***@***.***(mailto:2024 年 6 月 15 日星期六 20:07, Andrey Butirsky <<a href=)> 来信：

**Comment by bam80** [comment] 2024-06-15 12:48
> So I don't think these are all "out of standard"

Still, it might be.
Anyway, the standard literally states the behavior here, and seem doesn't give space to be interpreted differently.

Have a nice vacation!

**Comment by CoelacanthusHex** [comment] 2024-06-15 13:05
> > So I don't think these are all "out of standard"
> 
> Still, it might be. Anyway, the standard literally states the behavior here, and seem doesn't give space to be interpreted differently.

For standard, your card also violate the standard. If it need to return response data but the requester set N_e to 0 (without L_e), it should return SW1=61 with SW2 is left data size instead of 0x90'00 which means there is no error.

> 
> Have a nice vacation!

**Comment by bam80** [comment] 2024-06-15 13:10
> For standard, your card also violate the standard. If it need to return response data but the requester set N_e to 0 (without L_e), it should return SW1=61 with SW2 is left data size instead of 0x90'00 which means there is no error.

I'm not sure about it, might be.
Anyway, let's concentrate on the particular problem this issue was opened. The change suggested doesn't seem to be controversial.

**Comment by septs** [comment] 2024-06-15 13:15
I think @bam80 can try to become a reseller of eSTK.me and order a considerable quantity.
(May need 10k or 50k PCS or more)

Then @estkme will be motivated to help you with any problems. (i think so)

--------

Mobile Broadband Module manufacturers will also have similar requirements

**Comment by CoelacanthusHex** [comment] 2024-06-15 13:24
> > For standard, your card also violate the standard. If it need to return response data but the requester set N_e to 0 (without L_e), it should return SW1=61 with SW2 is left data size instead of 0x90'00 which means there is no error.
> 
> I'm not sure about it, might be. Anyway, let's concentrate on the particular problem this issue was opened. The change suggested doesn't seem to be controversial.

A APDU which needs response data can set N_e to any value including 0. It followed the standard. If N_r is greater than N_e, the card should send data as much as possible with SW1=61 to tell the host there is still some data need to transfer. For this case, N_e is 0, so if there is response data, N_r is always greater than N_e and no response data can be sent. So the card need to sent SW1=61 and SW2 is data size and waiting for the host request again. There is no violation or error in the host size. All APDU sent by lpac is valid, just your card violate the standard and can't deal with an valid and regular APDU flow.

**Comment by bam80** [comment] 2024-06-15 13:31
> If N_r is greater than N_e, the card should send data as much as possible with SW1=61

What I see from the Wiki for the Response data Length, it is:
> Nr (at most Ne) 

So N_r doesn't seem to be allowed to be greater than N_e, by the standard?

**Comment by septs** [comment] 2024-06-15 13:37
![p8](https://github.com/estkme-group/lpac/assets/3842474/42347fe1-086c-4ff3-b817-1820d1a3dcc1)
![p9](https://github.com/estkme-group/lpac/assets/3842474/996e8e1c-9126-4a25-a2f1-36aef99e8bf7)
![p10](https://github.com/estkme-group/lpac/assets/3842474/e4a34758-eaf4-49c4-b937-aac7c1ebc3d1)
![p11](https://github.com/estkme-group/lpac/assets/3842474/74819808-932d-49a0-ad56-8a9e001d739a)
![p12](https://github.com/estkme-group/lpac/assets/3842474/e1d7b145-9504-4c66-957d-771e4076c760)

**Comment by septs** [comment] 2024-06-15 13:40
full standard, see https://www.iso.org/standard/77180.html

**Comment by CoelacanthusHex** [comment] 2024-06-15 13:40
> > If N_r is greater than N_e, the card should send data as much as possible with SW1=61
> 
> What I see from the Wiki for the Response data Length, it is:
> 
> > Nr (at most Ne)
> 
> So N_r doesn't seem to be allowed to be greater than N_e, by the standard?

My bad. I means the response data size that need to be transferred, not N_r.

**Comment by bam80** [comment] 2024-06-15 13:49
@CoelacanthusHex OK I see your point.
Probably needs further investigation, but anyway - could we think of adding that `0x00` Le byte (as Windows does, BTW) - to make those cards work, also?

**Comment by septs** [comment] 2024-06-15 13:52
@bam80 I think you need to prove two things

1. This behavior does not affect the card mentioned by https://github.com/estkme-group/lpac/issues/118#issuecomment-2169488267
2. This behavior is widespread, not just the module or card you have.

**Closed** 2024-06-15 13:56 UTC
Labels: wontfix

**Comment by BeRealQueally** [comment] 2024-06-15 13:59
Close As this problem is not related to lpac,which means:
lpac is correctly handling the APDU from both send and recv.
And this issue is offtopic, which should not be fixed by lpac because:
NO other lpac-mbim user with a different module will encounter this problem.
